import type { SalesAuditEvent, SalesOpportunity } from "./salesOperations";

export type OpportunityWorkspaceProvisioningStatus = "provisioned" | "archived";
export type OpportunityWorkspaceProvisioningMode = "buyer-specific-protected-workspace";

export type OpportunityWorkspaceInvitationPolicy = {
  mode: "manual-onboarding-packet-only";
  directEmailSend: false;
  recommendedInitialRoles: Array<{
    email: string;
    role: "tenant-admin" | "pilot-lead" | "reviewer" | "observer";
    status: "pending-human-approval";
  }>;
  requiresAal2: true;
  requiresTenantAdminApproval: true;
  expiresInDays: number;
  noPhiBoundary: true;
};

export type SalesOpportunityWorkspaceProvisioning = {
  id: string;
  tenantId: string;
  intakeId: string;
  workspaceId: string;
  workspaceSlug: string;
  workspaceName: string;
  provisioningStatus: OpportunityWorkspaceProvisioningStatus;
  provisioningMode: OpportunityWorkspaceProvisioningMode;
  invitationPolicy: OpportunityWorkspaceInvitationPolicy;
  onboardingPlan: string[];
  retentionUntil: string;
  lastPacketGeneratedAt: string | null;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string | null;
  boundary: string;
};

export type SalesOpportunityWorkspaceProvisioningResult = {
  workspaceProvisioning: SalesOpportunityWorkspaceProvisioning;
  created: boolean;
  auditEventId: string | null;
  boundary: string;
};

export const opportunityWorkspaceProvisioningProofStackStatus =
  "aal2-opportunity-workspace-provisioning";
export const opportunityWorkspaceProvisioningPacketProofStackStatus =
  "aal2-audited-opportunity-workspace-packets";

export const opportunityWorkspaceProvisioningApiRoute =
  "/api/sales-operations/opportunities/{intakeId}/workspace-provisioning";
export const opportunityWorkspaceProvisioningPacketApiRoute =
  "/api/sales-operations/opportunities/{intakeId}/workspace-provisioning/packet";

export const opportunityWorkspaceProvisioningBoundary =
  "Opportunity Workspace Provisioning creates buyer-specific protected workspaces for governed synthetic enterprise evaluations only. It does not accept PHI, authorize live clinical execution, certify compliance, guarantee reimbursement, submit payer transactions, contact patients, or provide medical, legal, regulatory, or billing advice.";

export function isProvisioningEligible(opportunity: SalesOpportunity) {
  return ["qualified", "discovery", "proposal", "pilot-planning", "won"].includes(
    opportunity.pipelineStage
  );
}

export function workspaceMappingModeForOpportunity(opportunity: SalesOpportunity) {
  return opportunity.workspaceProvisioning
    ? "buyer-specific-workspace"
    : "default-synthetic-workspace";
}

export function workspaceSlugForOpportunity(opportunity: SalesOpportunity, fallbackWorkspaceSlug: string) {
  return opportunity.workspaceProvisioning?.workspaceSlug ?? fallbackWorkspaceSlug;
}

function appBase(baseUrl: string) {
  return baseUrl.replace(/\/$/, "");
}

export function buyerRoomRouteForProvisioning({
  appBaseUrl,
  intakeId,
  workspaceSlug
}: {
  appBaseUrl: string;
  intakeId: string;
  workspaceSlug: string;
}) {
  return `${appBase(appBaseUrl)}/pilot-workspace/access?workspace=${encodeURIComponent(
    workspaceSlug
  )}&opportunity=${encodeURIComponent(intakeId)}`;
}

export function buyerRoomPacketRouteForProvisioning({
  appBaseUrl,
  workspaceSlug
}: {
  appBaseUrl: string;
  workspaceSlug: string;
}) {
  return `${appBase(appBaseUrl)}/api/pilot-workspaces/${encodeURIComponent(
    workspaceSlug
  )}/buyer-room/packet`;
}

function markdownList(items: string[]) {
  return items.map((item) => `- ${item}`).join("\n");
}

function auditLines(events: SalesAuditEvent[]) {
  if (events.length === 0) return "- No recent sales audit events are visible for this opportunity.";

  return events
    .slice(0, 20)
    .map((event) => `- ${event.createdAt}: ${event.eventType} by ${event.actorUserId}`)
    .join("\n");
}

export function buildOpportunityWorkspaceProvisioningPacket({
  generatedAt,
  auditEventId,
  generatedBy,
  opportunity,
  provisioning,
  appBaseUrl,
  auditEvents
}: {
  generatedAt: string;
  auditEventId: string;
  generatedBy: string;
  opportunity: SalesOpportunity;
  provisioning: SalesOpportunityWorkspaceProvisioning;
  appBaseUrl: string;
  auditEvents: SalesAuditEvent[];
}) {
  const buyerRoomRoute = buyerRoomRouteForProvisioning({
    appBaseUrl,
    intakeId: opportunity.intakeId,
    workspaceSlug: provisioning.workspaceSlug
  });
  const buyerRoomPacketRoute = buyerRoomPacketRouteForProvisioning({
    appBaseUrl,
    workspaceSlug: provisioning.workspaceSlug
  });

  return `# SCRIMED Opportunity Workspace Provisioning Packet

## Packet Control
- Generated: ${generatedAt}
- Packet audit event ID: ${auditEventId}
- Generated by: ${generatedBy}
- Opportunity ID: ${opportunity.intakeId}
- Proof status: ${opportunityWorkspaceProvisioningPacketProofStackStatus}
- Data boundary: business-contact and workflow-scope only

## Buyer-Specific Workspace
- Organization: ${opportunity.payload.organization.name}
- Buyer contact: ${opportunity.payload.contact.fullName}
- Buyer email: ${opportunity.payload.contact.workEmail}
- Workspace name: ${provisioning.workspaceName}
- Workspace slug: ${provisioning.workspaceSlug}
- Workspace status: ${provisioning.provisioningStatus}
- Provisioning mode: ${provisioning.provisioningMode}
- Buyer room route: ${buyerRoomRoute}
- Buyer room packet API: ${buyerRoomPacketRoute}
- Retention until: ${provisioning.retentionUntil}

## Invitation And Access Policy
- Delivery mode: ${provisioning.invitationPolicy.mode}
- Direct email send enabled: ${provisioning.invitationPolicy.directEmailSend ? "yes" : "no"}
- Tenant-admin approval required: ${provisioning.invitationPolicy.requiresTenantAdminApproval ? "yes" : "no"}
- AAL2 required: ${provisioning.invitationPolicy.requiresAal2 ? "yes" : "no"}
- Invitation expiry: ${provisioning.invitationPolicy.expiresInDays} days
- Recommended initial roles: ${provisioning.invitationPolicy.recommendedInitialRoles
    .map((role) => `${role.email} as ${role.role} (${role.status})`)
    .join(", ")}

## Onboarding Plan
${markdownList(provisioning.onboardingPlan)}

## Buyer Scope
- Offer interest: ${opportunity.payload.scope.offerInterest}
- Timeline: ${opportunity.payload.scope.timeline}
- Workflow targets: ${opportunity.payload.scope.workflowTargets.join(", ")}
- Readiness needs: ${opportunity.payload.scope.readinessNeeds.join(", ")}
- Governance requirements: ${opportunity.payload.scope.governanceRequirements.join(", ")}
- Interoperability context: ${opportunity.payload.scope.interoperabilityContext || "To be confirmed"}
- Pilot goals: ${opportunity.payload.scope.pilotGoals}

## Required Controls Before Buyer Access
- Confirm buyer sponsor, workflow owner, legal/privacy/security reviewer, and SCRIMED owner.
- Keep all evaluation data synthetic or business-scope only.
- Use tenant-admin approval for any invitation, role change, packet release, or access review.
- Record demo readiness, TrustOps, buyer-room, and enterprise proof packets before paid expansion.
- Block PHI, autonomous diagnosis, payer submission, patient outreach, and production connector use until separately approved.

## Recent Sales Audit Events
${auditLines(auditEvents)}

## Boundary
${provisioning.boundary}

${opportunityWorkspaceProvisioningBoundary}

This packet is a non-binding implementation-readiness artifact. Final scope, pricing, legal terms, security requirements, access permissions, and production authorization require written buyer and SCRIMED approval.
`;
}
