/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated-compatible for Next.js TypeScript projects.
// Do not edit this file directly unless the Next.js type references change.
